### ISSUE TITLE
Remove $media-queries usage

### ISSUE THREAD

**Issue by jayarnielsen** [rideRTD/rtd-style#8]
@danandrade What is the purpose of the `$media-queries` variable? It doesn't seem to have one because it is always set to true. Recommending we remove it and any references to it entirely.

**Comment by danandrade** [comment]
This is legacy code from when we had to support IE8 which was surprisingly not that long ago. It was also used for the vendor stylesheets as their sites were usually never fully responsive. I think it is safe to remove it now though and all references.
